[project]
name = "val-mal-bot"
version = "1.0.0"
description = "Valin Malach's bot for Twitch/Discord"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.62",
    "discord>=2.3.2",
    "fastapi>=0.118.0",
    "httpx[http2]>=0.28.1",
    "orjson>=3.11.3",
    "pendulum>=3.1.0",
    "polars>=1.34.0",
    "psutil>=7.1.0",
    "pydantic>=2.11.10",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "sentry-sdk>=2.39.0",
    "truststore>=0.10.4",
    "uvicorn[standard]>=0.37.0",
    "xmltodict>=1.0.2",
]
