[project]
name = "val-mal-bot"
version = "1.0.0"
description = "Valin Malach's bot for Twitch/Discord"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.62",
    "discord>=2.3.2",
    "fastapi>=0.116.2",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.9",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.1",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "sentry-sdk>=2.38.0",
    "truststore>=0.10.4",
    "uvicorn>=0.35.0",
]
