[project]
name = "val-mal-bot"
version = "1.0.0"
description = "Valin Malach's bot for Twitch/Discord"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.62",
    "discord>=2.3.2",
    "fastapi>=0.117.1",
    "httpx>=0.28.1",
    "orjson>=3.11.3",
    "pendulum>=3.1.0",
    "polars>=1.33.1",
    "pydantic>=2.11.9",
    "python-dotenv>=1.1.1",
    "sentry-sdk>=2.38.0",
    "truststore>=0.10.4",
    "uvicorn[standard]>=0.36.0",
    "xmltodict>=1.0.2",
]
